### PR TITLE
Added basic Stats feature

### PR DESCRIPTION
**Pull request by aklife97**
I have added a basic stats functionality.
issue #10 
stats

### CODE REVIEW

**Comment by Mte90** [comment]
:-D

**Comment by aklife97** [comment]
Should I add a basic bar graph sort of thing to display the Stats
like
Licence        : |||||||||
Non-License: |||||
Total            : |||||||||||||||||||

**Comment by Mte90** [comment]
no the number is perfect maybe in the console a progressbar is useful.

**Comment by aklife97** [comment]
as in the % repos processed?

**Comment by Mte90** [comment]
uhm will be very interesting in case

**Comment by aklife97** [comment]
I actually have kind of made the progress bar thing, the only downside being you have to use a custom print function whenever you print just after progress bar is peinted. Will it be fine?

**Comment by Mte90** [comment]
is not a problem, as you can see is a simple script so improve the code itself is only a best fast :-D

**Comment by aklife97** [comment]
Okay! Will send a pull request.

**Pull request merged**
