### PR TITLE
Add git hook on repo init

### LINKED ISSUE #21: Git hooks
It will be helpful to have a git hooks installed globally when is executed `git init` to remember to download a license.

### PR DESCRIPTION
**Pull request by revolter**
_WIP_

This adds a post package install script that:
- [x] makes a backup of the current `init.templatedir` git config
- [x] creates a git template folder and sets it for the `init.templatedir` git config
- [x] copies the hooks folder in the created git template folder

Todo:
- [x] extract the license file presence check from [cmd.py](../blob/master/ghlicense/cmd.py)'s `main()` function
- [x] add the pre commit git hook implementation
- [x] add the git commit hook self removal when a license file is detected

Closes #21.

### CODE REVIEW

**Comment by revolter** [comment]
@Mte90, The pre commit hook should force the user to create a license file or only warn him before every commit?

**Comment by Mte90** [comment]
Good point maybe is better warn and ask for create it?

**Comment by revolter** [comment]
I'm thinking the same.

**Comment by revolter** [comment]
@Mte90, It's done 😄  Please review it when you have some time.

**Comment by Mte90** [comment]
Seems good but to check the hooks installed there is a way?
This hook will be installed globally or on every package?

**Comment by revolter** [comment]
> but to check the hooks installed there is a way?

What do you mean? If the user can see them? Or programmatically?

> This hook will be installed globally or on every package?

This hook is added to a git template which is used when you run `git init`, in which case, the generated `.git/hooks` folder will have template's hooks.

So basically it's "declared" globally, but installed in each repository. For example, if one repository adds a license file, only that repository's hook will get self removed, so other repositories would still print the warning.

**Comment by revolter** [comment]
Don't merge it just yet, as I found a problem.

**Comment by revolter** [comment]
Fixed the problem. Were my answers clear or do you want me to explain them better? 😄

**Comment by Mte90** [comment]
Ok probably is better to add that point about the installation global in the readme and for me is perfect :-D

**Comment by revolter** [comment]
Like [this](https://github.com/revolter/GH-License/blob/feature/git-hook/README.md#install)?

**Comment by Mte90** [comment]
Yeah!

**Comment by revolter** [comment]
Next one coming soon 😉

**Pull request merged**
