### PR TITLE
Scan export as file

### PR DESCRIPTION
**Pull request by aklife97**
Fix to issue #2 

Screenshot:
screenshot from 2016-09-28 19-54-53

### CODE REVIEW

**Comment by Mte90** [comment]
Very cool maybe the report name need to contain some info like the user in scanning and maybe the choice by parameter to export with a custom name

**Comment by aklife97** [comment]
@Mte90 Should the user in scanning be there in the report name? If yes, then what should the name of the file be given we have an option for custom name of file?

**Comment by Mte90** [comment]
I think that the ideal name will be [user]-gh-license-report

**Comment by Mte90** [comment]
Perfect!
maybe the help text needs an update to remember the fact there is that feature

**Comment by aklife97** [comment]
Does this do the work?

**Comment by Mte90** [comment]
Yeah!

**Pull request merged**
